In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data=pd.read_csv("reklam.csv")
data.head()

sıra     TV  radyo  gazete  satış
0     1  230.1   37.8    69.2   22.1
1     2   44.5   39.3    45.1   10.4
2     3   17.2   45.9    69.3    9.3
3     4  151.5   41.3    58.5   18.5
4     5  180.8   10.8    58.4   12.9

In [4]:
x=data.iloc[:,1:-1].values

In [5]:
x

array([[230.1,  37.8,  69.2],
       [ 44.5,  39.3,  45.1],
       [ 17.2,  45.9,  69.3],
       [151.5,  41.3,  58.5],
       [180.8,  10.8,  58.4],
       [  8.7,  48.9,  75. ],
       [ 57.5,  32.8,  23.5],
       [120.2,  19.6,  11.6],
       [  8.6,   2.1,   1. ],
       [199.8,   2.6,  21.2],
       [ 66.1,   5.8,  24.2],
       [214.7,  24. ,   4. ],
       [ 23.8,  35.1,  65.9],
       [ 97.5,   7.6,   7.2],
       [204.1,  32.9,  46. ],
       [195.4,  47.7,  52.9],
       [ 67.8,  36.6, 114. ],
       [281.4,  39.6,  55.8],
       [ 69.2,  20.5,  18.3],
       [147.3,  23.9,  19.1],
       [218.4,  27.7,  53.4],
       [237.4,   5.1,  23.5],
       [ 13.2,  15.9,  49.6],
       [228.3,  16.9,  26.2],
       [ 62.3,  12.6,  18.3],
       [262.9,   3.5,  19.5],
       [142.9,  29.3,  12.6],
       [240.1,  16.7,  22.9],
       [248.8,  27.1,  22.9],
       [ 70.6,  16. ,  40.8],
       [292.9,  28.3,  43.2],
       [112.9,  17.4,  38.6],
       [ 97.2,   1.5,  30. ],
       [26

In [6]:
y=data.iloc[:,-1].values

In [7]:
y

array([22.1, 10.4,  9.3, 18.5, 12.9,  7.2, 11.8, 13.2,  4.8, 10.6,  8.6,
       17.4,  9.2,  9.7, 19. , 22.4, 12.5, 24.4, 11.3, 14.6, 18. , 12.5,
        5.6, 15.5,  9.7, 12. , 15. , 15.9, 18.9, 10.5, 21.4, 11.9,  9.6,
       17.4,  9.5, 12.8, 25.4, 14.7, 10.1, 21.5, 16.6, 17.1, 20.7, 12.9,
        8.5, 14.9, 10.6, 23.2, 14.8,  9.7, 11.4, 10.7, 22.6, 21.2, 20.2,
       23.7,  5.5, 13.2, 23.8, 18.4,  8.1, 24.2, 15.7, 14. , 18. ,  9.3,
        9.5, 13.4, 18.9, 22.3, 18.3, 12.4,  8.8, 11. , 17. ,  8.7,  6.9,
       14.2,  5.3, 11. , 11.8, 12.3, 11.3, 13.6, 21.7, 15.2, 12. , 16. ,
       12.9, 16.7, 11.2,  7.3, 19.4, 22.2, 11.5, 16.9, 11.7, 15.5, 25.4,
       17.2, 11.7, 23.8, 14.8, 14.7, 20.7, 19.2,  7.2,  8.7,  5.3, 19.8,
       13.4, 21.8, 14.1, 15.9, 14.6, 12.6, 12.2,  9.4, 15.9,  6.6, 15.5,
        7. , 11.6, 15.2, 19.7, 10.6,  6.6,  8.8, 24.7,  9.7,  1.6, 12.7,
        5.7, 19.6, 10.8, 11.6,  9.5, 20.8,  9.6, 20.7, 10.9, 19.2, 20.1,
       10.4, 11.4, 10.3, 13.2, 25.4, 10.9, 10.1, 16

In [21]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.5,random_state=1)

In [22]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [23]:
lr.fit(xtrain,ytrain)

LinearRegression()

In [24]:
yhead=lr.predict(xtest)

In [25]:
yhead

array([21.7144191 , 16.31946756,  7.61144573, 17.51552859, 18.4231577 ,
       23.70478159, 16.36326138, 13.36302745,  9.3093825 , 17.24940044,
       14.43409766,  9.97075444, 17.05385906, 16.92957121, 14.89083942,
       15.76861525, 12.45320066, 16.82967474, 11.36747984, 17.90516623,
        9.3056371 , 13.27895217,  9.06140695, 10.45631852, 11.44727099,
       14.89368485, 10.01295912, 19.22972751, 18.20489823, 16.93717407,
       21.4479602 , 14.52666212, 16.27951473, 12.23718409, 19.76772638,
       15.25203457, 13.66798622, 10.01121912, 20.89289597,  7.67398379,
        3.81569153,  7.2431229 ,  6.19782935, 18.39495443,  8.69636579,
       14.0887491 , 15.25871676, 20.28014839, 20.55124536, 19.54579159,
       23.96599297, 14.93545072,  6.93808495, 19.92421365, 18.58126109,
       12.35620374, 13.92302002,  6.30609889, 15.03398852,  9.79738133,
       11.99824622, 11.97110019,  8.79910522, 21.2492442 , 23.12105865,
       12.71490631,  6.67011164, 17.96344808, 16.31525142,  8.96

In [26]:
ytest

array([23.8, 16.6,  9.5, 14.8, 17.6, 25.5, 16.9, 12.9, 10.5, 17.1, 14.5,
       11.3, 17.4, 16.7, 13.4, 15.9, 12.9, 12.8,  9.5, 18.4, 10.7, 12.5,
        8.5, 11.5, 11.9, 14.9, 10.1, 18.9, 19.6, 15.9, 23.2, 11.9, 17.3,
       11.7, 20.2, 15.5, 11.5, 11. , 22.3,  7.6,  5.3,  8.7,  6.7, 19. ,
        5.5, 14.6, 14.6, 21.5, 22.6, 19.7, 25.4, 15.2,  6.6, 21.2, 17.4,
       12.6, 12.2,  7.2, 13.4,  9.6, 12.2, 13.4,  5.3, 20.7, 24.4,  7.2,
        8.8, 19.2, 14.8,  9.5, 20.2, 21.7, 26.2,  7.3,  8. , 15.9,  9.2,
        9.4, 22.2, 15.5, 15.6, 11.2, 12.3, 11.6,  9.9,  9.7, 11.3,  5.7,
       17.3, 14.9, 17.2, 25.4, 13.3, 10.3, 19. , 14.7,  7.6, 12.8, 10.9,
       11.7])

In [27]:
data.head()

sıra     TV  radyo  gazete  satış
0     1  230.1   37.8    69.2   22.1
1     2   44.5   39.3    45.1   10.4
2     3   17.2   45.9    69.3    9.3
3     4  151.5   41.3    58.5   18.5
4     5  180.8   10.8    58.4   12.9

In [28]:
lr.predict([[300,100,750]])

array([38.08333101])

In [29]:
lr.predict([[100,100,500]])

array([28.03306329])

In [30]:
from sklearn.metrics import mean_squared_error,r2_score
rmse=np.sqrt(mean_squared_error(ytest,yhead))
rmse

1.5247832862198565

In [31]:
r2=r2_score(ytest,yhead)

In [32]:
r2

0.9133071815302057